### PR TITLE
Begin Updating Documentation

### PR DESCRIPTION
**Pull request by ghost**
I have updated the front-page README to better reflect Dennis Kowalski's recommendation to "bring a box of doughnut first" and better attract any and all contributors.

### CODE REVIEW

**Comment by michaelgill1969** [comment]
@cryonicsdg I'm not sure what you see when I request your review.  If you have any trouble, I just need your feedback on the changes I made to what you will see in the README at the bottom of the page here:
[https://github.com/michaelgill1969/checkin](https://github.com/michaelgill1969/checkin)

**Comment by michaelgill1969** [comment]
@cryonicsdg I integrated your suggested changes.

**Comment by cryonicsdg** [comment]
Awesome - thank you Michael.

**Comment by michaelgill1969** [comment]
You were up late.  Sleep in!

**Comment by cryonicsdg** [comment]
:-)

I wish. Too much to do.

But thanks for noticing and mentioning it, brother!

**Pull request merged**
